//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhatHanhSach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongNoNXB
    {
        public int Id { get; set; }
        public Nullable<int> IdNXB { get; set; }
        public Nullable<double> TongTienThanhToan { get; set; }
        public Nullable<double> TongTienConNo { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual NhaXuatBan NhaXuatBan { get; set; }
    }
}
