//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhatHanhSach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtBaoCaoDL
    {
        public int Id { get; set; }
        public Nullable<int> IdBaoCao { get; set; }
        public Nullable<int> IdSach { get; set; }
        public Nullable<double> DonGiaXuat { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<int> SoLuongTonDotTruoc { get; set; }
        public Nullable<double> TongTienNhap { get; set; }
        public Nullable<int> SoLuongXuat { get; set; }
        public Nullable<double> TongTienXuat { get; set; }
        public Nullable<int> SoLuongCon { get; set; }
        public Nullable<double> TongTienNo { get; set; }
    
        public virtual BaoCaoDL BaoCaoDL { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
