//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhatHanhSach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtPhieuXuat
    {
        public int Id { get; set; }
        public Nullable<int> IdPhieuXuat { get; set; }
        public Nullable<int> IdSach { get; set; }
        public Nullable<int> SoLuongXuat { get; set; }
        public Nullable<double> DonGiaXuat { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual PhieuXuat PhieuXuat { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
