//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhatHanhSach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtThanhToan
    {
        public int Id { get; set; }
        public Nullable<int> IdThanhToan { get; set; }
        public Nullable<int> IdSach { get; set; }
        public Nullable<double> DonGiaNhap { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<int> SoLuongTonDotTruoc { get; set; }
        public Nullable<double> TongTienNhap { get; set; }
        public Nullable<int> SoLuongXuat { get; set; }
        public Nullable<double> TongTienXuat { get; set; }
        public Nullable<int> SoLuongCon { get; set; }
        public Nullable<double> TienNo { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual ThanhToan ThanhToan { get; set; }
    }
}
