//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhatHanhSach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TonKho
    {
        public int Id { get; set; }
        public Nullable<int> IdSach { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> TangGiam { get; set; }
    
        public virtual Sach Sach { get; set; }
    }
}
