//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhatHanhSach.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongNoNXB
    {
        public string Id { get; set; }
        public string MaNXB { get; set; }
        public string MaPhieuThanhToan { get; set; }
        public Nullable<double> TongTienThanhToan { get; set; }
        public Nullable<double> TongTienConNo { get; set; }
    
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual ThanhToan ThanhToan { get; set; }
    }
}
