//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhatHanhSach.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtBaoCaoDL
    {
        public int Id { get; set; }
        public string MaBaoCao { get; set; }
        public string MaSach { get; set; }
        public Nullable<double> DonGiaXuat { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<int> SoLuongCon { get; set; }
        public Nullable<double> TienNo { get; set; }
    
        public virtual BaoCaoDL BaoCaoDL { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
