//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhatHanhSach.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtThanhToan
    {
        public int Id { get; set; }
        public string MaPhieuThanhToan { get; set; }
        public string MaSach { get; set; }
        public Nullable<int> SoLuongXuat { get; set; }
        public Nullable<double> DonGiaNhap { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual ThanhToan ThanhToan { get; set; }
    }
}
