//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhatHanhSach.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuXuat()
        {
            this.CtPhieuXuats = new HashSet<CtPhieuXuat>();
        }
    
        public string MaPhieuXuat { get; set; }
        public string MaDaiLy { get; set; }
        public string NguoiNhan { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
        public Nullable<double> TongTien { get; set; }
        public System.DateTime ThoiGianXuat { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtPhieuXuat> CtPhieuXuats { get; set; }
        public virtual DaiLy DaiLy { get; set; }
    }
}
