//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhatHanhSach.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNhap()
        {
            this.CtPhieuNhaps = new HashSet<CtPhieuNhap>();
        }
    
        public string MaPhieuNhap { get; set; }
        public string MaNXB { get; set; }
        public string NguoiGiao { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<System.DateTime> ThoiGianNhap { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtPhieuNhap> CtPhieuNhaps { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
    }
}
