//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhatHanhSach.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThanhToan()
        {
            this.CongNoNXBs = new HashSet<CongNoNXB>();
            this.CtThanhToans = new HashSet<CtThanhToan>();
        }
    
        public string MaPhieuThanhToan { get; set; }
        public string MaNXB { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public Nullable<System.DateTime> ThoiGianLapPhieu { get; set; }
        public Nullable<double> TongTienThanhToan { get; set; }
        public Nullable<double> TongTienConNo { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongNoNXB> CongNoNXBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtThanhToan> CtThanhToans { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual TinhTrang TinhTrang1 { get; set; }
    }
}
